version: "3.3"

services:
  server:
    build:
      dockerfile: ./Dockerfile
      # dockerfile: ./Dockerfile.runtime
      context: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ./:/code:cached
      - ~/.cache/huggingface/:/root/.cache/huggingface/
    ports:
      - "7860:7860"
